name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label:
      - "chore"
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "enhancement"
    branch:
      - '/feat\/.+/'

  # version-resolver labels
  # if a PR only fixes some bugs the patch should be updated
  - label: "patch"
    branch:
      - '/fix\/.+/'
      - '/chore\/.+/'
  # if a PR adds a feature the minor should be updated (when no breaking changes)
  - label: "minor"
    branch:
      - '/feat\/.+/'
  # if a PR adds a breaking-change feature the major should be updated
  - label: "major"
    body:
      - '/BREAKING\ CHANGE/'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
